@extends('layouts.admin')
@section('title', 'Edit Asset - ' . config('app.name'))
@section('page_title', 'Edit Fixed Asset')
@section('content')
<div class="mb-4"><a href="{{ route('admin.fixed-assets.index') }}" class="text-sm text-gray-500 hover:text-emerald-600">&larr; Back to Assets</a></div>
<div class="bg-white rounded-xl border p-6 max-w-2xl">
    <form method="POST" action="{{ route('admin.fixed-assets.update', $fixedAsset) }}">@csrf @method('PATCH')
        <div class="grid grid-cols-2 gap-4">
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Asset Number <span class="text-red-500">*</span></label><input type="text" name="asset_number" value="{{ old('asset_number', $fixedAsset->asset_number) }}" required class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Asset Tag</label><input type="text" name="asset_tag" value="{{ old('asset_tag', $fixedAsset->asset_tag) }}" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"></div>
            <div class="col-span-2"><label class="block text-xs font-medium text-gray-600 mb-1">Name <span class="text-red-500">*</span></label><input type="text" name="name" value="{{ old('name', $fixedAsset->name) }}" required class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Category</label><select name="category" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500">@php $cats = ['it_equipment'=>'IT Equipment','furniture'=>'Furniture','vehicle'=>'Vehicle','machinery'=>'Machinery','building'=>'Building','other'=>'Other']; @endphp@foreach($cats as $v=>$l)<option value="{{ $v }}" @selected(old('category', $fixedAsset->category) === $v)>{{ $l }}</option>@endforeach</select></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Location</label><input type="text" name="location" value="{{ old('location', $fixedAsset->location) }}" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Acquisition Date <span class="text-red-500">*</span></label><input type="date" name="acquisition_date" value="{{ old('acquisition_date', $fixedAsset->acquisition_date->format('Y-m-d')) }}" required class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Acquisition Cost <span class="text-red-500">*</span></label><input type="number" name="acquisition_cost" value="{{ old('acquisition_cost', $fixedAsset->acquisition_cost) }}" required step="0.01" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Salvage Value</label><input type="number" name="salvage_value" value="{{ old('salvage_value', $fixedAsset->salvage_value) }}" step="0.01" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Useful Life (Years) <span class="text-red-500">*</span></label><input type="number" name="useful_life_years" value="{{ old('useful_life_years', $fixedAsset->useful_life_years) }}" required min="1" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Depreciation Method</label><select name="depreciation_method" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"><option value="straight_line" @selected(old('depreciation_method', $fixedAsset->depreciation_method) === 'straight_line')>Straight Line</option><option value="declining_balance" @selected(old('depreciation_method', $fixedAsset->depreciation_method) === 'declining_balance')>Declining Balance</option></select></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Status</label><select name="status" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"><option value="in_use" @selected(old('status', $fixedAsset->status) === 'in_use')>In Use</option><option value="under_maintenance" @selected(old('status', $fixedAsset->status) === 'under_maintenance')>Under Maintenance</option><option value="disposed" @selected(old('status', $fixedAsset->status) === 'disposed')>Disposed</option><option value="written_off" @selected(old('status', $fixedAsset->status) === 'written_off')>Written Off</option></select></div>
        </div>
        <div class="mt-6 flex items-center gap-3">
            <button type="submit" class="px-5 py-2 bg-emerald-600 text-white text-sm font-medium rounded-lg hover:bg-emerald-700">Update Asset</button>
            <a href="{{ route('admin.fixed-assets.index') }}" class="px-5 py-2 bg-gray-100 text-gray-700 text-sm font-medium rounded-lg hover:bg-gray-200">Cancel</a>
        </div>
    </form>
</div>
@endsection
