@extends('layouts.admin')
@section('title', 'Edit Vehicle - ' . config('app.name'))
@section('page_title', 'Edit Vehicle')
@section('content')
<div class="mb-4"><a href="{{ route('admin.fleet.index') }}" class="text-sm text-gray-500 hover:text-emerald-600">&larr; Back to Fleet</a></div>
<div class="bg-white rounded-xl border p-6 max-w-2xl">
    <form method="POST" action="{{ route('admin.fleet.update', $vehicle) }}">@csrf @method('PATCH')
        <div class="grid grid-cols-2 gap-4">
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Vehicle Number <span class="text-red-500">*</span></label><input type="text" name="vehicle_number" value="{{ old('vehicle_number', $vehicle->vehicle_number) }}" required class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Registration Number <span class="text-red-500">*</span></label><input type="text" name="registration_number" value="{{ old('registration_number', $vehicle->registration_number) }}" required class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Make <span class="text-red-500">*</span></label><input type="text" name="make" value="{{ old('make', $vehicle->make) }}" required class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Model <span class="text-red-500">*</span></label><input type="text" name="model" value="{{ old('model', $vehicle->model) }}" required class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Year</label><input type="number" name="year" value="{{ old('year', $vehicle->year) }}" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Color</label><input type="text" name="color" value="{{ old('color', $vehicle->color) }}" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Vehicle Type</label><select name="vehicle_type" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"><option value="car" @selected(old('vehicle_type', $vehicle->vehicle_type) === 'car')>Car</option><option value="truck" @selected(old('vehicle_type', $vehicle->vehicle_type) === 'truck')>Truck</option><option value="van" @selected(old('vehicle_type', $vehicle->vehicle_type) === 'van')>Van</option><option value="motorcycle" @selected(old('vehicle_type', $vehicle->vehicle_type) === 'motorcycle')>Motorcycle</option></select></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Fuel Type</label><select name="fuel_type" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"><option value="diesel" @selected(old('fuel_type', $vehicle->fuel_type) === 'diesel')>Diesel</option><option value="petrol" @selected(old('fuel_type', $vehicle->fuel_type) === 'petrol')>Petrol</option><option value="electric" @selected(old('fuel_type', $vehicle->fuel_type) === 'electric')>Electric</option><option value="hybrid" @selected(old('fuel_type', $vehicle->fuel_type) === 'hybrid')>Hybrid</option></select></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Fuel Capacity (L)</label><input type="number" name="fuel_capacity" value="{{ old('fuel_capacity', $vehicle->fuel_capacity) }}" step="0.01" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Odometer (km)</label><input type="number" name="odometer_reading" value="{{ old('odometer_reading', $vehicle->odometer_reading) }}" step="0.01" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Purchase Date</label><input type="date" name="purchase_date" value="{{ old('purchase_date', $vehicle->purchase_date?->format('Y-m-d')) }}" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Purchase Price</label><input type="number" name="purchase_price" value="{{ old('purchase_price', $vehicle->purchase_price) }}" step="0.01" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Insurance Expiry</label><input type="date" name="insurance_expiry" value="{{ old('insurance_expiry', $vehicle->insurance_expiry?->format('Y-m-d')) }}" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Registration Expiry</label><input type="date" name="registration_expiry" value="{{ old('registration_expiry', $vehicle->registration_expiry?->format('Y-m-d')) }}" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"></div>
            <div><label class="block text-xs font-medium text-gray-600 mb-1">Status</label><select name="status" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:ring-2 focus:ring-emerald-500"><option value="active" @selected(old('status', $vehicle->status) === 'active')>Active</option><option value="maintenance" @selected(old('status', $vehicle->status) === 'maintenance')>Maintenance</option><option value="retired" @selected(old('status', $vehicle->status) === 'retired')>Retired</option></select></div>
        </div>
        <div class="mt-6 flex items-center gap-3">
            <button type="submit" class="px-5 py-2 bg-emerald-600 text-white text-sm font-medium rounded-lg hover:bg-emerald-700">Update Vehicle</button>
            <a href="{{ route('admin.fleet.index') }}" class="px-5 py-2 bg-gray-100 text-gray-700 text-sm font-medium rounded-lg hover:bg-gray-200">Cancel</a>
        </div>
    </form>
</div>
@endsection
